# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 

Name:       mfc-firmware
Summary:    Binary mfc firmware common for all samsung targets
Version:    0.0.7
Release:    1
Group:      TO_BE/FILLED_IN
License:    Apache License, Version 2.0
Source0:    %{name}-%{version}.tar.gz
ExclusiveArch: %arm

%define debug_package %{nil}

%description
binary mfc firmware common for all samsung targets

%package e4412 
Summary:    binary mfc firmware specific to e4412
Group:      TO_BE/FILLED

%description e4412
binary mfc firmware specific to e4412.

%prep
%setup -q

%build

%install
rm -rf %{buildroot}

mkdir -p %{buildroot}/lib/firmware

cp -af mfc-firmware-e4412/mfc_fw.bin %{buildroot}/lib/firmware/mfc_fw_e4412.bin

cp -af mfc-firmware-e4412/mfc_fw.bin %{buildroot}/lib/firmware/mfc_fw.bin

%files e4412
%manifest mfc-firmware-e4412.manifest
%defattr(-,root,root,-)
/lib/firmware/mfc_fw.bin
/lib/firmware/mfc_fw_e4412.bin

%post e4412
mv /lib/firmware/mfc_fw_e4412.bin /lib/firmware/mfc_fw.bin

%preun e4412
mv /lib/firmware/mfc_fw.bin /lib/firmware/mfc_fw_e4412.bin
